# Generated by Django 3.0.5 on 2020-05-13 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=2, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronicas.Documento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronicas.Evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='documentos',
            field=models.ManyToManyField(through='cronicas.Fuente', to='cronicas.Documento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='individuos',
            field=models.ManyToManyField(to='cronicas.Individuo'),
        ),
    ]
