# Generated by Django 3.0.5 on 2020-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('LB', 'Libro'), ('VD', 'Video'), ('OT', 'Otro')], max_length=2, null=True),
        ),
    ]
