# Generated by Django 3.0.5 on 2020-05-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0002_auto_20200514_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='autor',
        ),
        migrations.AddField(
            model_name='documento',
            name='autor',
            field=models.ManyToManyField(to='cronicas.Individuo'),
        ),
    ]
