# Generated by Django 3.0.5 on 2021-02-25 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0004_auto_20200515_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('creacion', models.DateTimeField(blank=True, null=True)),
                ('desaparicion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individuo',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individuo',
            name='desaparicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cronicas.Ubicacion'),
        ),
    ]
